behaviors:
  GetKey:
    trainer_type: ppo
    time_horizon: 256 #nagyobbat pl 256 (32)
    max_steps: 1e6 #(2e6)
    hyperparameters:
      learning_rate: 1e-4 #3e-4 utolsó lehetőség (1e-4)
      batch_size: 512 #1024,2048
      buffer_size: 5000 #20000 10ep
      num_epoch: 3 
    network_settings:
      normalize: true
      num_layers: 3 
      hidden_units: 256 
    reward_signals:        
        extrinsic:
            gamma: 0.9
            strength: 1.0
        # curiosity:
            # gamma: 0.99
            # strength: 0.02
            # network_settings:
                # hidden_units: 256
            # learning_rate: 0.0003
    summary_freq: 25000 #25000 pontok a tensor gráfon (50000)
    threaded: true    
    
torch_settings:
  device: cpu

#elsőnek max step 1000 --> heuristic test után